### ISSUE TITLE
Dev CI compilation fails, despite code compiling everywhere else

### ISSUE THREAD

**Issue by jakezweifler** [inQWIRE/QuantumLib#23]
When compiling the dev version of the project, an error is thrown near the beginning of compilation when trying to "pull docker image." Despite this fail, all other versions compile successfully. I also tried recompiling code that succeeded on dev 10 days ago, and the compilation failed, suggesting that the problem is external to the project. How should I fix this?

**Comment by khieta** [comment]
@jakezweifler Why did you mark this a closed? It looks like the dev version is still failing. 

@k4rtik Do you have any suggestions?

**Comment by k4rtik** [comment]
I took a look, it seems like because  in our yml file we have:
https://github.com/inQWIRE/QuantumLib/blob/7eef08e6d1fc023b1cbfd813b52535e26b00876c/.github/workflows/coq-action.yml#L20

but they have recently upgraded the OCaml version to `4.12`+, see https://hub.docker.com/r/coqorg/coq/tags?page=1&name=dev

I will see how to get the CI to work again.
